### PR TITLE
Don't override previous_tab and indent_backwards shortcuts on OSX

### PR DESCRIPTION
**Pull request by mason-stewart**
Prior to this commit, the shortcuts for these `paredit_wrap_square` and `paredit_wrap_curly` were overriding the OS X shortcuts for the `previous_tab` and `indent_backwards` commands built into Sublime.

The addition of `ctrl+` definitely makes these two shortcuts more cumbersome, but I think it's best not to override two of the most used built-in Sublime shortcuts.

This also disables Paredit's `ctrl+super+f` shortcut, which conflicts with Sublime's fullscreen shortcut on OS X. As far as I can tell, `paredit_forward` and `paredit_backward` mimic functionality that is already built into OS X and available almost globally via `ctrl+option+f` and `ctrl+option+b`. Should we maybe disable `paredit_backward` in the OS X keyboard defaults, as well? 

Happy to change this to another set shortcut if you have a better idea :dancer:

### CODE REVIEW

**Comment by odyssomay** [comment]
Hmm. I'm very torn about this. On one hand, it's very bad to override default shortcuts. On the other, I would like the plugin to match the cheatsheet as much as possible. I would say, if we change it, I think it would be better if we simply used _alt_ instead of _cmd_ (as is already done with the _super+s_ shortcut). As opposed to using _ctrl+cmd_. That way, it would be more similar to the cheatsheet. I guess it would still require documentation, but I feel it would make more sense that way.

When it comes to fullscreen, is _F11_ not a shortcut for that in osx?

Anyway, appreciate the contribution. :+1:
I'm sorry that it took so long for me to answer, but I'm very torn as I mentioned.

**Comment by mason-stewart** [comment]
I should be the one saying sorry for the late response this time :D 
Good call on suggesting `alt`, it works fine, is closer to the cheatsheet, and is less crazy on the left hand :+1:.

I do think that the average Sublime user won't get much out of the cheat sheet, anyway. It's a bit cryptic, and most non-Emacs background people are going miss the meaning of things like `C-M-f`. It's probably going to be necessary to write your own version of that doc in more Sublime-friendly terms, especially if you're going to have slight cross-platform differences in the shortcuts.

Also, in Sublime on OSX, _F11_ isn't used for full screen, as you mentioned. I don't think you actually need that shortcut on OS X anyway, though, since you can do exact same cursor movement by default in almost any text on OS X with `ctrl+option+f` (same goes for jumping one word backwards with `ctrl+option+b`).

**Comment by xpe** [comment]
@odyssomay Are you on Mac OS X? If you want, I can test since I am.

**Comment by odyssomay** [comment]
> I do think that the average Sublime user won't get much out of the cheat sheet, anyway. It's a bit cryptic, and most non-Emacs background people are going miss the meaning of things like C-M-f. It's probably going to be necessary to write your own version of that doc in more Sublime-friendly terms, especially if you're going to have slight cross-platform differences in the shortcuts.

Yes, this is the best way I think - use alt instead and make a new cheatsheet.

**Comment by odyssomay** [comment]
So I merged the request but reinstated the paredit-forward shortcut. Honestly I almost feel like all shortcuts using _cmd_ should use alt instead, since only problems seem to come from using _cmd_. What do you think about that?

**Comment by mason-stewart** [comment]
I think that probably makes sense. There may be a few shortcuts that are already in use even with _alt_, but there will certainly be less collisions than with _cmd_

**Pull request merged**
